"""`next`: main, the pin move, then people's commits.

`next` is the move to the upcoming upstream release, opened early (ADR 0009,
decision 8). This file does the git work that keeps it in that shape, in a
scratch worktree and on a detached HEAD. It never pushes and never touches a
remote: the result is a commit, recorded under a local ref, and a description
of what happened. Publishing is a separate step (publish.py), so a run that
stops halfway here leaves `next` exactly as it was.

The shape:

    main ── pin move ── a person's commit ── another ...

  * The pin move is one commit and stays the first after `main`. It carries
    an `OpenShell-Release:` trailer, which is how it is recognised; its title
    can be reworded without confusing anything.
  * When the target changes (a newer pre-release, or the stable release), the
    new move is committed on top as an `amend!` commit and folded into the
    first one with `git rebase --autosquash`. An `amend!` commit is a fixup
    that also replaces the message, so the title names the release the commit
    now pins.
  * When `main` has moved, `next` is rebased onto it first. When it has not,
    it is not: a rebase changes every commit id for nothing.

Conflicts. A lock file (`backend/go.sum`, `frontend/package-lock.json`) is
regenerated by the tool that owns it and the rebase carries on. Anything else
aborts the rebase and is reported; nobody's work is guessed at.
"""

import json
import os
import re
import shutil
import subprocess
import tempfile

import pinmove

NEXT_REF = "refs/remotes/origin/next"
# Where the prepared commit is kept until it is pushed. A commit made on a
# detached HEAD in a worktree that is then removed is otherwise unreachable.
LOCAL_REF = "refs/upstream/next"

TRAILER = "OpenShell-Release"
TRAILER_RE = re.compile(r"^%s: (\S+)\s*$" % TRAILER, re.M)

BOT_NAME = "github-actions[bot]"
BOT_EMAIL = "41898282+github-actions[bot]@users.noreply.github.com"

# Settings a rebase or a commit can pick up from whoever runs this. They are
# pinned so that a run on a laptop behaves like a run on a runner: no editor,
# no hook, no signing prompt, no conflict resolution remembered from earlier.
GIT_CONFIG = (
    "user.name=" + BOT_NAME,
    "user.email=" + BOT_EMAIL,
    "commit.gpgsign=false",
    "core.hooksPath=/dev/null",
    "core.editor=true",
    "sequence.editor=true",
    "rerere.enabled=false",
    "rebase.autoStash=false",
    "rebase.updateRefs=false",
    "advice.detachedHead=false",
)

# More stops than any real `next` has commits. A rebase that stops this often
# is not converging.
MAX_STOPS = 500


class GitError(Exception):
    """git did something this file does not know how to carry on from."""


class Git(object):
    """git in one directory, with the settings above and nothing interactive."""

    def __init__(self, cwd):
        self.cwd = cwd

    def run(self, *args, **kwargs):
        check = kwargs.pop("check", True)
        # A hook or a wrapper may export GIT_DIR and friends, which would point
        # every command at some other repository.
        env = {key: value for key, value in os.environ.items() if not key.startswith("GIT_")}
        env.update(GIT_EDITOR="true", GIT_SEQUENCE_EDITOR="true", GIT_TERMINAL_PROMPT="0")
        command = ["git"]
        for setting in GIT_CONFIG:
            command += ["-c", setting]
        command += list(args)
        done = subprocess.run(
            command, cwd=self.cwd, env=env, universal_newlines=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE
        )
        if check and done.returncode != 0:
            raise GitError("`git %s` failed in %s:\n%s%s" % (" ".join(args), self.cwd, done.stdout, done.stderr))
        return done

    def out(self, *args):
        return self.run(*args).stdout.strip()

    def maybe(self, *args):
        """The command's output, or None when it failed."""
        done = self.run(*args, check=False)
        return done.stdout.strip() if done.returncode == 0 else None


def commits_between(git, base, tip):
    """The commits of base..tip, oldest first, each with the release its trailer names."""
    text = git.run("log", "--reverse", "--format=%H%x1f%s%x1f%an%x1f%B%x1e", "%s..%s" % (base, tip)).stdout
    found = []
    for record in text.split("\x1e"):
        record = record.strip("\n")
        if not record:
            continue
        sha, subject, author, body = record.split("\x1f", 3)
        trailer = TRAILER_RE.search(body)
        found.append({"sha": sha, "subject": subject, "author": author, "pin": trailer.group(1) if trailer else None})
    return found


def people(commits):
    """Every commit that is not the pin move: the work people put on `next`."""
    return [commit for commit in commits if not commit["pin"]]


def pins_at(git, ref):
    """The pins document a commit holds, or None when it has none that parses."""
    text = git.maybe("show", "%s:%s" % (ref, pinmove.PINS))
    if text is None:
        return None
    try:
        return json.loads(text)
    except ValueError:
        return None


def _is_ancestor(git, ancestor, descendant):
    return git.run("merge-base", "--is-ancestor", ancestor, descendant, check=False).returncode == 0


def _rebasing(git):
    for name in ("rebase-merge", "rebase-apply"):
        path = git.out("rev-parse", "--git-path", name)
        if os.path.isdir(path if os.path.isabs(path) else os.path.join(git.cwd, path)):
            return True
    return False


def _stopped_at(git):
    sha = git.maybe("rev-parse", "--verify", "-q", "REBASE_HEAD")
    if not sha:
        return None
    return {"sha": sha, "subject": git.out("log", "-1", "--format=%s", sha)}


def _rebase(git, args, lockfiles, regenerated, stage):
    """Run a rebase to its end. None when it finished; the conflict when it could not.

    lockfiles: {path: callable(tree) -> other paths it rewrote}. A stop whose
    conflicts are all in these files is resolved by regenerating them. Any
    other stop aborts the rebase, which puts the worktree back where it was.
    """
    done = git.run(*args, check=False)
    for _ in range(MAX_STOPS):
        if done.returncode == 0:
            return None
        if not _rebasing(git):
            raise GitError("`git %s` failed without leaving a rebase to resolve:\n%s%s" % (" ".join(args), done.stdout, done.stderr))
        files = git.out("diff", "--name-only", "--diff-filter=U").splitlines()
        stopped = _stopped_at(git)
        if not files:
            output = done.stdout + done.stderr
            git.run("rebase", "--abort", check=False)
            raise GitError("the rebase stopped with nothing in conflict, which is not expected:\n%s" % output)
        if any(path not in lockfiles for path in files):
            git.run("rebase", "--abort")
            return {"stage": stage, "files": files, "commit": stopped}
        try:
            for path in files:
                # Take the side that is already built, so the file parses, then
                # let the tool that owns it write what the merged manifest needs.
                git.run("checkout", "--ours", "--", path)
                also = lockfiles[path](git.cwd)
                git.run("add", "--", path, *also)
                regenerated.append(path)
        except Exception:
            git.run("rebase", "--abort", check=False)
            raise
        done = git.run("rebase", "--continue", check=False)
    git.run("rebase", "--abort", check=False)
    raise GitError("the rebase stopped more than %d times; giving up" % MAX_STOPS)


def _stage_pin_move(git):
    """Stage the pin move's files. True when there is something to commit.

    The move may change PIN_PATHS and nothing else. A change anywhere else
    means a tool did something it was not asked to, and it is not committed.
    """
    changed = [text[3:] for text in git.run("status", "--porcelain").stdout.splitlines() if text.strip()]
    foreign = [path for path in changed if path not in pinmove.PIN_PATHS]
    if foreign:
        raise GitError(
            "the pin move changed files it must not: %s. Nothing was committed." % ", ".join(sorted(foreign))
        )
    if not changed:
        return False
    git.run("add", "--", *changed)
    return git.run("diff", "--cached", "--quiet", check=False).returncode != 0


def _commit(git, message):
    """Commit what is staged, signed off, with exactly this message."""
    directory = tempfile.mkdtemp(prefix="upstream-message-")
    try:
        path = os.path.join(directory, "message")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(message)
        # -s: this repository requires a DCO sign-off on every commit.
        git.run("commit", "-s", "-q", "-F", path)
    finally:
        shutil.rmtree(directory, ignore_errors=True)


def lockfile_regenerators(run=None, echo=None):
    """{lock file: how to regenerate it}, for a tree that is stopped mid-rebase.

    `go mod tidy` and `npm install --package-lock-only --ignore-scripts` read
    the manifest and ask a registry. Neither builds or runs a dependency.
    """
    run = run or pinmove.run_command

    def go_sum(tree):
        pinmove.must(run, ["go", "mod", "tidy"], os.path.join(tree, "backend"), echo)
        # tidy may also correct go.mod: two tidy go.mod files do not always
        # merge into a tidy one.
        return [pinmove.GO_MOD]

    def package_lock(tree):
        pinmove.must(
            run,
            ["npm", "install", "--package-lock-only", "--ignore-scripts", "--no-audit", "--no-fund"],
            os.path.join(tree, "frontend"),
            echo,
        )
        return []

    return {pinmove.GO_SUM: go_sum, "frontend/package-lock.json": package_lock}


def prepare(repo, target, mover, message, lockfiles=None, main_ref="HEAD", next_ref=NEXT_REF, spent=False):
    """Work out what `next` should be, and build it.

    repo: a clone that has `main_ref` and, if the branch exists, `next_ref`.
    target: the plan's target, or None when upstream has nothing ahead of main.
    mover(tree, target): the pin move (pinmove.apply with its tools bound).
    message(target, moved): the pin commit's message, trailer included.
    spent: the pull request from `next`, at the commit `next` is on, was
    merged. What is on the branch is in `main` already, whatever the merge
    method made of the commit ids.

    Returns what happened as a dict. `action` is one of:

      create    `next` did not exist; `sha` is main plus the pin move
      update    `sha` is what `next` should be force-pushed to
      none      `next` is already right
      conflict  it could not be rebased or re-pinned; `conflict` says where
      delete    nothing but the bot's commit is on it and nothing is ahead
      leave     nothing is ahead, and people's commits are on it
    """
    lockfiles = lockfiles or {}
    git = Git(repo)
    main = git.out("rev-parse", "--verify", "%s^{commit}" % main_ref)
    existing = git.maybe("rev-parse", "--verify", "-q", "%s^{commit}" % next_ref)
    outcome = {
        "action": "none",
        "reason": "",
        "main": main,
        "next": existing,
        "sha": None,
        "rebased": False,
        "pin_moved": False,
        "moved": None,
        "regenerated": [],
        "conflict": None,
        "people": [],
        "pins": pins_at(git, existing) if existing else None,
    }

    if target is None:
        if existing is None:
            outcome["reason"] = "upstream has no release ahead of main, and there is no next branch"
            return outcome
        outcome["people"] = people(commits_between(git, main, existing))
        if spent:
            outcome.update(action="delete", reason="its pull request was merged, and upstream has no release ahead of main")
        elif not outcome["people"]:
            outcome.update(
                action="delete",
                reason="nothing but the pin move is on it, and upstream has no release ahead of main",
            )
        else:
            outcome.update(
                action="leave",
                reason="upstream has no release ahead of main, but commits that are not the pin move are on it",
            )
        return outcome

    # A spent `next` holds what main already has. It starts again from main.
    start = main if existing is None or spent else existing
    scratch = tempfile.mkdtemp(prefix="upstream-next-")
    tree = os.path.join(scratch, "tree")
    git.run("worktree", "add", "--detach", tree, start)
    work = Git(tree)
    try:
        if start != main and not _is_ancestor(work, main, "HEAD"):
            conflict = _rebase(
                work, ["rebase", "--empty=drop", main], lockfiles, outcome["regenerated"], "rebase"
            )
            if conflict:
                outcome.update(action="conflict", conflict=conflict)
                outcome["people"] = people(commits_between(git, main, existing))
                outcome["reason"] = "next could not be rebased onto main"
                return outcome
            outcome["rebased"] = True

        commits = commits_between(work, main, "HEAD")
        pin = commits[0] if commits and commits[0]["pin"] else None
        conflict = None
        if commits and pin is None:
            # Someone made `next` by hand, so no pin move starts it. Make the
            # move on main and put their commits back on top of it.
            tip = work.out("rev-parse", "HEAD")
            work.run("checkout", "-q", "--detach", main)
            moved = mover(tree, target)
            if _stage_pin_move(work):
                _commit(work, message(target, moved))
                base = work.out("rev-parse", "HEAD")
                conflict = _rebase(
                    work, ["rebase", "--empty=drop", "--onto", base, main, tip], lockfiles, outcome["regenerated"], "pin"
                )
                outcome["pin_moved"] = True
            else:
                work.run("checkout", "-q", "--detach", tip)
        else:
            moved = mover(tree, target)
            if _stage_pin_move(work):
                text = message(target, moved)
                if pin is None:
                    _commit(work, text)
                else:
                    # Fold the new move into the pin commit, message included.
                    _commit(work, "amend! %s\n\n%s" % (pin["subject"], text))
                    conflict = _rebase(
                        work,
                        ["rebase", "-i", "--autosquash", "--empty=drop", main],
                        lockfiles,
                        outcome["regenerated"],
                        "pin",
                    )
                outcome["pin_moved"] = True
        outcome["moved"] = moved
        if conflict:
            outcome.update(action="conflict", conflict=conflict, pin_moved=False)
            outcome["people"] = people(commits_between(git, main, existing)) if existing else []
            outcome["reason"] = "the pin on next could not be moved to OpenShell %s" % target["version"]
            return outcome

        new = work.out("rev-parse", "HEAD")
        after = commits_between(work, main, "HEAD")
        outcome["people"] = after[1:] if after and after[0]["pin"] else after
        outcome["sha"] = new
        outcome["pins"] = pins_at(work, "HEAD")
        git.run("update-ref", LOCAL_REF, new)
        if existing is None:
            outcome.update(action="create", reason="there was no next branch")
        elif new == existing:
            outcome.update(action="none", reason="next is on main and already pins OpenShell %s" % target["version"])
        else:
            reasons = []
            if spent:
                reasons.append("its pull request was merged, so it starts again from main")
            if outcome["rebased"]:
                reasons.append("main has moved")
            if outcome["pin_moved"]:
                reasons.append("the pin moves to OpenShell %s" % target["version"])
            outcome.update(action="update", reason=" and ".join(reasons) or "next changed")
        return outcome
    finally:
        git.run("worktree", "remove", "--force", tree, check=False)
        shutil.rmtree(scratch, ignore_errors=True)
        git.run("worktree", "prune", check=False)
